#!/usr/bin/env bash
# deploy-signoz.sh — install/upgrade SigNoz from the official SigNoz/charts
# Helm repo (spec #42, slice #44 packaging; slice #47 wires the k8s deploy
# path). Pinned at chart 0.129.0 (appVersion v0.129.0 — Compose parity).
#
# Usage: deploy-signoz.sh [--namespace N] [--values extra-values.yaml]...
#
# - namespace defaults to the `namespace` key in values/signoz.yaml
#   (harness6-system, per the slice #43 values-layer contract).
# - Secrets come from the `harness6-secrets` Secret created by bootstrap.sh;
#   values/signoz.yaml references them via secretKeyRef (SIGNOZ_JWT_SECRET,
#   SIGNOZ_USER_ROOT_PASSWORD). Impersonation flags ride in via
#   values-user.yaml (generated by bootstrap.sh).
# - After rollout the script health-gates the SigNoz UI (in-cluster probe
#   against the /api/v1/version endpoint) and prints the auto-assigned
#   NodePorts for the UI (8080) and OTLP gRPC/HTTP (4317/4318).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VALUES_FILE="${SCRIPT_DIR}/values/signoz.yaml"
# HARNESS6_VALUES_USER overrides the generated values file (tests stub it;
# production uses the file bootstrap.sh generates next to this script).
VALUES_USER="${HARNESS6_VALUES_USER:-${SCRIPT_DIR}/values-user.yaml}"
CHART_REPO_NAME="signoz"
CHART_REPO_URL="https://charts.signoz.io"
CHART_REF="${CHART_REPO_NAME}/signoz"
CHART_VERSION="0.129.0" # matches Compose's SigNoz v0.129.0 (spec #42)
RELEASE_NAME="signoz"
NAMESPACE=""
EXTRA_VALUES_ARGS=()
HEALTH_ATTEMPTS="${HEALTH_ATTEMPTS:-60}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-10}"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
info() { printf '%s\n' "$*"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --namespace) NAMESPACE="$2"; shift 2 ;;
    --values) EXTRA_VALUES_ARGS+=(--values "$2"); shift 2 ;;
    *) die "unknown argument: $1 (use --namespace or --values)" ;;
  esac
done

[[ -f "$VALUES_FILE" ]] || die "values file not found: $VALUES_FILE"

command -v kubectl >/dev/null 2>&1 || die "kubectl is required but not installed"
command -v helm >/dev/null 2>&1 || die "helm is required but not installed"

[[ -f "$VALUES_USER" ]] || die "values-user.yaml not found at ${VALUES_USER} — run bootstrap.sh first"

if [[ -z "$NAMESPACE" ]]; then
  NAMESPACE="$(sed -n 's/^namespace: //p' "$VALUES_USER" | head -n1 | tr -d "'\"")"
fi
[[ -n "$NAMESPACE" ]] || die "no namespace key in ${VALUES_USER}; pass --namespace"

info "==> namespace: ${NAMESPACE}"
kubectl get namespace "$NAMESPACE" >/dev/null 2>&1 \
  || kubectl create namespace "$NAMESPACE" \
  || die "failed to ensure namespace ${NAMESPACE}"

# Idempotent chart-repo bootstrap (no-op when already added).
helm repo list 2>/dev/null | grep -q "^${CHART_REPO_NAME}[[:space:]]" \
  || helm repo add "$CHART_REPO_NAME" "$CHART_REPO_URL" >/dev/null
helm repo update >/dev/null

info "==> helm upgrade --install ${RELEASE_NAME} (${CHART_REF} ${CHART_VERSION})"
helm upgrade --install "$RELEASE_NAME" "$CHART_REF" \
  --version "$CHART_VERSION" \
  --namespace "$NAMESPACE" \
  --values "$VALUES_FILE" \
  --values "$VALUES_USER" \
  "${EXTRA_VALUES_ARGS[@]+"${EXTRA_VALUES_ARGS[@]}"}" \
  --wait --timeout 20m

info "==> waiting for ${RELEASE_NAME} rollouts"
for kind in deployment statefulset; do
  # Scope to the release via label selector so unrelated workloads in the
  # shared namespace never stall this wait (pattern from deploy-milvus.sh).
  resources="$(kubectl get "$kind" -n "$NAMESPACE" \
    -l "app.kubernetes.io/instance=${RELEASE_NAME}" -o name 2>/dev/null)" || resources=""
  for res in $resources; do
    kubectl wait "$res" -n "$NAMESPACE" --for=condition=available --timeout=10m
  done
done

# Health gate (spec #42 deploy-order contract): poll the SigNoz UI's
# version API from inside the cluster, so the probe works regardless of
# how the UI Service is published (NodePort, LoadBalancer, Ingress).
info "==> health-gating SigNoz UI (in-cluster probe)"
ui_port="$(kubectl get service -n "$NAMESPACE" \
  -l "app.kubernetes.io/instance=${RELEASE_NAME},app.kubernetes.io/component=signoz" \
  -o 'jsonpath={range .items[*].spec.ports[*]}{.port}{"\n"}{end}' 2>/dev/null | head -n1 || true)"
[[ -n "$ui_port" ]] || ui_port="8080"
probe_ok=0
for attempt in $(seq 1 "$HEALTH_ATTEMPTS"); do
  if kubectl run "signoz-healthcheck-${attempt}" -n "$NAMESPACE" \
      --rm -i --restart=Never --quiet \
      --image=curlimages/curl --command -- \
      curl -fsS -o /dev/null "http://signoz.${NAMESPACE}.svc:${ui_port}/api/v1/version" 2>/dev/null; then
    probe_ok=1
    break
  fi
  if [[ "$attempt" -eq "$HEALTH_ATTEMPTS" ]]; then
    break
  fi
  sleep "$HEALTH_INTERVAL"
done
if [[ "$probe_ok" -ne 1 ]]; then
  info "==> warning: SigNoz UI did not answer ${HEALTH_ATTEMPTS} health probes; continuing — inspect pods in ${NAMESPACE}"
else
  info "==> SigNoz UI healthy"
fi

# Report the workstation-facing endpoints. nodePort is auto-assigned by the
# cluster; report what it actually got. In-cluster ports (8080/4317/4318)
# key the lookup by containerPort/servicePort.
while read -r svc_port node_port; do
  case "$svc_port" in
    8080) info "==> SigNoz UI:            http://<node>:${node_port}" ;;
    4317) info "==> OTLP gRPC (4317):     <node>:${node_port}" ;;
    4318) info "==> OTLP HTTP (4318):     <node>:${node_port}" ;;
  esac
done < <(kubectl get service -n "$NAMESPACE" \
  -l "app.kubernetes.io/instance=${RELEASE_NAME}" \
  -o 'jsonpath={range .items[*].spec.ports[*]}{.port}{" "}{.nodePort}{"\n"}{end}' 2>/dev/null || true)
info "==> done"
